font_family FantasqueSansM Nerd Font Mono Bold
font_size 14.0
bold_font auto
italic_font auto
bold_italic_font auto

background_opacity 0.75
dynamic_background_opacity 1
confirm_os_window_close 0

# Animated cursor
cursor_trail 1

#tab bar
tab_bar_style powerline
tab_powerline_style slanted
active_tab_foreground   #141414
active_tab_background   #afb979
inactive_tab_foreground #feffd3
inactive_tab_background #262626
tab_bar_background      #141414

# change to x11 or wayland or leave auto
linux_display_server auto

scrollback_lines 2000
wheel_scroll_min_lines 1

enable_audio_bell no

window_padding_width 4

selection_foreground none
selection_background none

#foreground #dddddd
#background #000000
#cursor #dddddd

#colors
background #141414
foreground #feffd3
cursor #ffffff
selection_background #303030
color0 #141414
color8 #262626
color1 #c06c43
color9 #dd7c4c
color2 #afb979
color10 #cbd88c
color3 #c2a86c
color11 #e1c47d
color4 #444649
color12 #5a5d61
color5 #b4be7b
color13 #d0db8e
color6 #778284
color14 #8a989a
color7 #feffd3
color15 #feffd3
selection_foreground #141414
