;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;==========================================================

[global/wm]
include-file = $HOME/.config/polybar/colors.ini
include-file = $HOME/.config/polybar/modules.ini

[bar/top]
#monitor = HDMI-1
width =  98%
height = 26
padding-left =1
padding-right =0
background = ${colors.background}
foreground = ${colors.foreground}
bottom = false
border-top-size = 7
border-bottom-size = 7
border-top-color = ${colors.background}
border-bottom-color = ${colors.background}
offset-x = 1%
offset-y = 0.5%
fixed-center = true
line-size = 3

wm-restack = i3
enable-ipc = true
override-redirect = false 

modules-left = filesystem xworkspaces
modules-center = xwindow 
modules-right = alsa battery temperature space cpu mem space round-left time round-right space tray space powermenu

font-0 = JetBrainsMono Nerd Font:style=Bold:pixelsize=13;3
font-1 = JetBrainsMono Nerd Font:size=18;5
font-2 = Material Design Icons:style=Bold:size=13;3
font-3 = unifont:fontformat=truetype:size=13:antialias=true;

